force-app/main/default/objects/Account/fields/Billed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billed_Amount__c</fullName>
    <label>Billed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contracts</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>Due_Amount__c</fullName>
    <label>Due_Amount</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed_Amount</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Govt_Funds__c.field-meta.xml
<CustomField>
    <fullName>Govt_Funds__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Govt Funds</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Contract already billed</errorMessage>
        <filterItems>
            <field>$Source.IsItBilled__c</field>
            <operation>notEqual</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Govt_Funds__c</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/IsItBilled__c.field-meta.xml
<CustomField>
    <fullName>IsItBilled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is It Billed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/TotalPaidAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalPaidAmount__c</fullName>
    <label>TotalPaidAmount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>All Construction related expenses are lodged here.</description>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>Expense No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Ammount__c.field-meta.xml
<CustomField>
    <fullName>Ammount__c</fullName>
    <label>Ammount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Contacts__c.field-meta.xml
<CustomField>
    <fullName>Contacts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contracts</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Govt_Funds__c/Govt_Funds__c.object-meta.xml
<CustomObject>
    <description>Government bills and  Personal amount will loaded</description>
    <label>Govt Funds</label>
    <nameField>
        <label>Funds Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Govt Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Govt_Funds__c/fields/Billed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Billed_Amount__c</fullName>
    <label>Billed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Govt_Funds__c/fields/TotalContractsAmt__c.field-meta.xml
<CustomField>
    <fullName>TotalContractsAmt__c</fullName>
    <label>Total Contracts Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Project_GovtBillAmtCalculation.cls
public class Project_GovtBillAmtCalculation {
    
        
    
    public static void totalAmtandDueCal(Map<Id,Govt_Funds__c> govtFudsNewMap){
 
      
        Set<Id> contractsIds=new Set<Id>();
        Map<Id,Decimal> totalCntrctAmt=new  Map<Id,Decimal> ();
        list<Govt_Funds__c> updFundsLst=new list<Govt_Funds__c>();

       	
        for(Contract__c cntrct:[SELECT Id, Project__c, Contact__c, Due_Amount__c, Fixed_Amount__c, TotalPaidAmount__c, Description__c, Start_date__c, End_Date__c, Title__c, IsItBilled__c, Govt_Funds__c FROM Contract__c
		where Govt_Funds__c IN : govtFudsNewMap.keySet()]){
            contractsIds.add(cntrct.id);
            if(totalCntrctAmt.containsKey(cntrct.Govt_Funds__c)){
               // Decimal expAmt=Integer.valueof(totalAmt.get(cntrct.Govt_Funds__c));
                Decimal ctrexpAmt=totalCntrctAmt.get(cntrct.Govt_Funds__c);
                ctrexpAmt=ctrexpAmt+Decimal.valueOf(cntrct.TotalPaidAmount__c);
                //  system.debug('==ctrexpAmt=='+ctrexpAmt);
                totalCntrctAmt.put(cntrct.Govt_Funds__c,ctrexpAmt);
            }else
              totalCntrctAmt.put(cntrct.Govt_Funds__c,Decimal.valueOf(cntrct.TotalPaidAmount__c));
                    
         
        
         } 
        
       // system.debug('==totalCntrctAmt=='+totalCntrctAmt);
    Map<id,id> accContrlMap=new Map<id,id>();
        for(Govt_Funds__c con: govtFudsNewMap.values()){
            con.TotalContractsAmt__c=totalCntrctAmt.get(con.Id);
            updFundsLst.add(con);
          
         }
       // system.debug('==updFundsLst=='+updFundsLst);
   // Updating Billed amount at account level
     list<account> updacclst=new list<account>();
       Map<Id,Decimal> ttlActBilledAmt=new  Map<Id,Decimal> (); 
        for(Expense__c exp:[select id,Ammount__c,Project__c,Contacts__c,Contracts__c from Expense__c 
                         where  Contracts__c IN :contractsIds]){
     
                if(ttlActBilledAmt.containsKey(exp.Project__c)){
                Decimal ctrexpAmt=totalCntrctAmt.get(exp.Project__c);
                ctrexpAmt=ctrexpAmt+exp.Ammount__c;
                ttlActBilledAmt.put(exp.Project__c,ctrexpAmt);
            }else
              ttlActBilledAmt.put(exp.Project__c,exp.Ammount__c);  
                                   
         }
        for(Account acc:[select id,Billed_Amount__c from account where id IN :ttlActBilledAmt.keySet()]){
            acc.Billed_Amount__c=ttlActBilledAmt.get(acc.id);
            updacclst.add(acc);
        }   
        if(!updacclst.isEmpty())
            update updacclst;
    }

}