force-app/main/default/objects/Contact/fields/Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>Due_Amount__c</fullName>
    <label>Due Amount</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed Amount</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/TotalPaidAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalPaidAmount__c</fullName>
    <label>Total Paid Amount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/Contract__c.object-meta.xml
<CustomObject>
    <label>Contracts</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contract__c/fields/Due_Amount__c.field-meta.xml
<CustomField>
    <fullName>Due_Amount__c</fullName>
    <label>Due_Amount</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Fixed_Amount__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Amount__c</fullName>
    <label>Fixed_Amount</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contract__c/fields/TotalPaidAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalPaidAmount__c</fullName>
    <label>TotalPaidAmount</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <description>All Construction related expenses are lodged here.</description>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>Expense No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Ammount__c.field-meta.xml
<CustomField>
    <fullName>Ammount__c</fullName>
    <label>Ammount</label>
    <precision>9</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Contacts__c.field-meta.xml
<CustomField>
    <fullName>Contacts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Contracts__c.field-meta.xml
<CustomField>
    <fullName>Contracts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contracts</label>
    <referenceTo>Contract__c</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Expenses</relationshipLabel>
    <relationshipName>Expenses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Project_AmountCalculation.cls
public class Project_AmountCalculation {
    
    public static void totalAmtandDueCal(Map<Id,Expense__c> expenseNewMap,Map<Id,Expense__c> expenseOldMap){
        Map<Id,Expense__c> expenseMap=new Map<Id,Expense__c>();
        if(Trigger.isdelete)
           expenseMap= expenseOldMap;
        else
          expenseMap= expenseNewMap;  
      
        Set<Id> contIds=new Set<Id>();
        Map<Id,Decimal> totalAmt=new  Map<Id,Decimal> ();
        list<Contact> upContLst=new list<Contact>();

        Set<Id> cntrtIds=new Set<Id>();
        Map<Id,Decimal> totalCntrctAmt=new  Map<Id,Decimal> ();
        list<Contract__c> updContractLst=new list<Contract__c>();
        
        for(Expense__c exp:expenseMap.values()){ 
            contIds.add(exp.Contacts__c);
            cntrtIds.add(exp.Contracts__c);
        }
        for(Expense__c exp:[select id,Ammount__c,Contacts__c,Contracts__c from Expense__c where Contacts__c IN : contIds OR Contracts__c IN :cntrtIds]){
            
            if(totalCntrctAmt.containsKey(exp.Contracts__c)){
               // Decimal expAmt=Integer.valueof(totalAmt.get(exp.Contacts__c));
                Decimal ctrexpAmt=totalCntrctAmt.get(exp.Contracts__c);
                ctrexpAmt=ctrexpAmt+exp.Ammount__c;
                totalCntrctAmt.put(exp.Contracts__c,ctrexpAmt);
            }else
              totalCntrctAmt.put(exp.Contracts__c,exp.Ammount__c);
                    
                    
                if(totalAmt.containsKey(exp.Contacts__c)){
                  // Decimal expAmt=Integer.valueof(totalAmt.get(exp.Contacts__c));
                   Decimal expAmt=totalAmt.get(exp.Contacts__c);
                   expAmt=expAmt+exp.Ammount__c;
                   totalAmt.put(exp.Contacts__c,expAmt);
               }else
                   totalAmt.put(exp.Contacts__c,exp.Ammount__c);
        
         } 
        
        for(Contact con:[select id,name,TotalPaidAmount__c,Fixed_Amount__c,Due_Amount__c from contact where id=:contIds]){
            con.TotalPaidAmount__c=String.valueof(totalAmt.get(con.Id));
          if(con.Fixed_Amount__c<>null)
           con.Due_Amount__c=String.valueOf(Integer.valueof(con.Fixed_Amount__c)-Integer.valueof(totalAmt.get(con.Id)));   
           
          upContLst.add(con);
        } 
        if(upContLst.size()>0)
          update upContLst;  
      
      
        
       for(Contract__c ctrt:[select id,name,Project__c,TotalPaidAmount__c,Fixed_Amount__c,Due_Amount__c from Contract__c  where id=:cntrtIds]){
        ctrt.TotalPaidAmount__c=String.valueof(totalCntrctAmt.get(ctrt.Id));
          if(ctrt.Fixed_Amount__c<>null)
          ctrt.Due_Amount__c=String.valueOf(Integer.valueof(ctrt.Fixed_Amount__c)-Integer.valueof(totalCntrctAmt.get(ctrt.Id)));   
           
          updContractLst.add(ctrt);
        } 
   
        if(updContractLst.size()>0)
        update updContractLst; 
   }
    
    public static void dueAmountCal(Map<Id,Expense__c> expenseNewLst,Map<Id,Expense__c> expenseOldLst){
        
    }

}